### ISSUE TITLE
Netbox v4.3.x compatibility

### ISSUE THREAD

**Issue by a084ed22** [ArnesSI/netbox-inventory#235]
It seems that the changes done to graphql are preventing the upgrade to v4.3. The following error is obtained when running upgrade.sh:

```
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_inventory/__init__.py", line 36, in ready
    super().ready()
  File "/opt/netbox/netbox/netbox/plugins/__init__.py", line 129, in ready
    if graphql_schema := self._load_resource('graphql_schema'):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/plugins/__init__.py", line 95, in _load_resource
    module = import_module(default_module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_inventory/graphql/__init__.py", line 1, in <module>
    from .schema import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_inventory/graphql/schema.py", line 12, in <module>
    from .types import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_inventory/graphql/types.py", line 17, in <module>
    from .filters import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_inventory/graphql/filters.py", line 3, in <module>
    from netbox.graphql.filter_mixins import autotype_decorator, BaseFilterMixin
ImportError: cannot import name 'autotype_decorator' from 'netbox.graphql.filter_mixins' (/opt/netbox/netbox/netbox/graphql/filter_mixins.py)
```

**Comment by hdse** [comment]
We have the same error.

**Comment by matejv** [comment]
Indeed, the plugin will require some fixes before it works with netbox 4.3. I'll take a look at what needs fixing in the coming days.

**Comment by basn** [comment]
Any update @matejv? need any help testing or something shout! :)

**Comment by a084ed22** [comment]
you can track #242. Pulling it in local_requirements.txt allows the update to complete. I'm seeing other issues in the netbox installation I manage so I'll be checking what they are due.

**Comment by srbri** [comment]
@basn In case you weren't sure, follow the instructions to install a development version per the readme, but change the path ending with master.tar.gz to netbox-43.tar.gz

Got me up and running, so far so good.

**Comment by basn** [comment]
Yeah, i wanted to make sure it was even a good idea to test first :)

**Comment by matejv** [comment]
To all waiting for the the release compatible with netbox 4.3... It's still coming soon :) Unfortunately I have been busy with other projects in the last few weeks. 

The current branch netbox-43 seems to work fine but the GraphQL changes in netbox mean that netbox-inventory needs a lot of updates in that area too. I don't use that part of the code and I haven't written it so I need to look into it a bit deeper to see what needs changing. If anyone else wants to have a go at it, you're more than welcome :)

**Comment by BartZimmo** [comment]
Hi,

@matejv, for our company plugin, the fix for 4.3 was to remove the "autotype_decorator" fields.
In the filters.py for your graphql, only keep the @strawberry and remove all the @autotype_d.

![Image](https://github.com/user-attachments/assets/1999bb45-4208-4ba5-af0f-47994272265a)

**Comment by ytjohn** [comment]
Would it be reasonable to drop graphql support? I know our group stopped using that capability of netbox-inventory when netbox 4 came out, opting instead for the dynamic field return.

**Comment by alasdairmuckart** [comment]
> [@cs-1](https://github.com/cs-1) havent gotten around to test it, we are thinking of removing the plugin but not decided yet.

When you say "removing the plugin" do you mean stop development of this altogether? 

Thanks.

**Comment by matejv** [comment]
> When you say "removing the plugin" do you mean stop development of this altogether?

Netbox inventory plugin is still under development. Though since the codebase has become quite large I'm not a fan of adding many more large features to it. I do try to follow new netbox releases to put out a compatible netbox-inventory version in decent time, however this is not always possible when I'm busy on other projects. Reports on broken functionality are welcome and speed-up getting a fixed version released. Pull requests with fixes are even more welcome :)

PS: I released [v2.4.1](https://github.com/ArnesSI/netbox-inventory/releases/tag/v2.4.1) that addresses some minor issues related to netbox 4.4.
